=== nicolasduminil/aws-camelk/aws-camelk-file/src/main/resources/xsd/money-transfer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.simplex-software.fr/money-transfer" xmlns:ss="http://www.simplex-software.fr/money-transfer"
        xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb" jaxb:extensionBindingPrefixes="xjc"
        jaxb:version="3.0" elementFormDefault="qualified">
  <annotation>
    <appinfo>
      <jaxb:globalBindings>
        <xjc:simple/>
        <jaxb:serializable/>
      </jaxb:globalBindings>
    </appinfo>
  </annotation>
  <simpleType name="BankAccountType" final="restriction">
    <restriction base="string">
      <enumeration value="SAVINGS" />
      <enumeration value="CHECKING" />
    </restriction>
  </simpleType>

  <complexType name="BankAddress">
    <attribute name="streetName" type="string" />
    <attribute name="streetNumber" type="string" />
    <attribute name="poBox" type="string" />
    <attribute name="cityName" type="string" />
    <attribute name="zipCode" type="string" />
    <attribute name="countryName" type="string" />
  </complexType>

  <complexType name="Bank">
    <sequence>
      <element name="bankAddresses" type="ss:BankAddress" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="bankName" type="string"/>
  </complexType>

  <complexType name="BankAccount">
    <sequence>
      <element name="bank" type="ss:Bank"/>
    </sequence>
    <attribute name="accountID" type="string" />
    <attribute name="accountType" type="ss:BankAccountType" />
    <attribute name="sortCode" type="string" />
    <attribute name="accountNumber" type="string" />
    <attribute name="transCode" type="string" />
  </complexType>

  <complexType name="MoneyTransfer">
    <sequence>
      <element name="reference" type="string"/>
      <element name="sourceAccount" type="ss:BankAccount"/>
      <element name="targetAccount" type="ss:BankAccount"/>
      <element name="amount" type="decimal" minOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="MoneyTransfers">
    <sequence>
      <element name="moneyTransfer" type="ss:MoneyTransfer" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <element name="moneyTransfers" type="ss:MoneyTransfers"></element>
</schema>

=== nicolasduminil/aws-camelk/aws-camelk-model/src/main/resources/xml/money-transfer.xml
<mon:moneyTransfer xmlns:mon="http://www.simplex-software.fr/money-transfer"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.simplex-software.fr/money-transfer ../xsd/money-transfer.xsd">
  <mon:reference>Tech Repairs</mon:reference>
  <mon:sourceAccount accountID="SG01" accountType="CHECKING" sortCode="04004" accountNumber="00050525712" transCode="03000">
    <mon:bank bankName="Société Générale">
      <mon:bankAddresses streetName="av. de Paris" streetNumber="18" poBox="Cedex" cityName="Montmorency" zipCode="95800" countryName="France"/>
    </mon:bank>
  </mon:sourceAccount>
  <mon:targetAccount accountID="ING01" accountType="SAVINGS" sortCode="08080" accountNumber="425091789" transCode="7BRE0">
    <mon:bank bankName="ING">
      <mon:bankAddresses streetName="blvd. Waterloo" streetNumber="381" poBox="INGPOBOX" cityName="Waterloo" zipCode="B1000" countryName="Belgium"/>
    </mon:bank>
  </mon:targetAccount>
  <mon:amount>1000.00</mon:amount>
</mon:moneyTransfer>
